version = 1

[[annotations]]
path = [
  ".gitignore",
  ".gitattributes",
  ".gitmodules",
  ".github/**",
  ".envrc",
  ".markdownlint.yaml",
  ".markdownlintignore",
  "Containerfile",
  "default.nix",
  "flake.lock",
  "flake.nix",
  "shell.nix",
  "vcpkg-configuration.json",
  "vcpkg.json",
  ".clang-format",
  ".clang-tidy",
  "CODEOWNERS",
  "hooks/**",
  "ci/**"
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"

[[annotations]]
path = ["launcher/package/**"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2026 Project Tick"

[[annotations]]
path = ["**/*.md", "doc/**"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2026 Project Tick"

[[annotations]]
path = ["cmake/**", "**/CMakeLists.txt"]
SPDX-License-Identifier = "BSD-3-Clause"
SPDX-FileCopyrightText = "Various authors"

[[annotations]]
path = [
  "branding/**",
  "launcher/resources/**"
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2026 Project Tick"

[[annotations]]
path = [
  "**/testdata/**"
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"

[[annotations]]
path = ["**/*.ui"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2026 Project Tick"

[[annotations]]
path = ["libraries/**/.gitignore"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"

[[annotations]]
path = ["CMakePresets.json"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2026 Project Tick"

[[annotations]]
path = ["nix/**"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "2026 Project Tick"

[[annotations]]
path = ["mnv/**"]
SPDX-License-Identifier = "Vim AND GPL-3.0-or-later"
SPDX-FileCopyrightText = "Bram Moolenaar & Vim Contributors & Project Tick"

[[annotations]]
path = ["archived/projt-launcher/**"]
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = "MultiMC Contributors & Prism Launcher Contributors & PolyMC Contributors & Project Tick"

[[annotations]]
path = ["archived/projt-modpack/**"]
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = "Project Tick"

[[annotations]]
path = ["archived/projt-minicraft-modpack/**"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "Project Tick"

[[annotations]]
path = ["archived/ptlibzippy/**"]
SPDX-License-Identifier = "Zlib"
SPDX-FileCopyrightText = "Zlib Contributors & Project Tick"

[[annotations]]
path = ["cmark/**"]
SPDX-License-Identifier = "BSD-2-Clause AND MIT AND CC-BY-SA-4.0"
SPDX-FileCopyrightText = "CMark Contributors & Project Tick"

[[annotations]]
path = ["corebinutils/**"]
SPDX-License-Identifier = "BSD-1-Clause AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause AND MIT"
SPDX-FileCopyrightText = "FreeBSD Contributors & Project Tick"

[[annotations]]
path = ["forgewrapper/**"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "ForgeWrapper Contributors & Project Tick"

[[annotations]]
path = ["neozip/**"]
SPDX-License-Identifier = "Zlib"
SPDX-FileCopyrightText = "Zlib Contributors & Zlib-ng Contributors & Project Tick"

[[annotations]]
path = ["tomlplusplus/**"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "Toml++ Contributors & Project Tick"

[[annotations]]
path = ["json4cpp/**"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "Json4C++ Contributors & Project Tick"

[[annotations]]
path = ["genqrcode/**"]
SPDX-License-Identifier = "LGPL-2.1-or-later"
SPDX-FileCopyrightText = "GenQRCode Contributors & Project Tick"

[[annotations]]
path = ["libnbtplusplus/**"]
SPDX-License-Identifier = "LGPL-3.0-or-later"
SPDX-FileCopyrightText = "libnbtplusplus Contributors & ljfa-ag & Project Tick"

[[annotations]]
path = ["meta/**"]
SPDX-License-Identifier = "MS-PL"
SPDX-FileCopyrightText = "MultiMC Contributors & PolyMC Contributors & PrismLauncher Contributors & Project Tick"

[[annotations]]
path = ["images4docker/**"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "Project Tick"

[[annotations]]
path = ["ofborg/**"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "NixOS Contributors & Project Tick"

[[annotations]]
path = ["GOVERNANCE.md",
        "GOVERNANCE",
        "CONTRIBUTING",
        "CODE_OF_CONDUCT",
        "README",
        "SECURITY",
        "TRADEMARK"
       ]
SPDX-License-Identifier = "LicenseRef-Project-Tick-Legal"
SPDX-FileCopyrightText = "2025-2026 Project Tick"
