/* SPDX-FileCopyrightText: 2026 Project Tick
 * SPDX-FileContributor: Project Tick
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 *   MeshMC - A Custom Launcher for Minecraft
 *   Copyright (C) 2026 Project Tick
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <minecraft/VersionFile.h>
#include <minecraft/PackProfile.h>
#include <minecraft/Library.h>
#include <QJsonDocument>
#include <ProblemProvider.h>

class OneSixVersionFormat
{
  public:
	// version files / profile patches
	static VersionFilePtr versionFileFromJson(const QJsonDocument& doc,
											  const QString& filename,
											  const bool requireOrder);
	static QJsonDocument versionFileToJson(const VersionFilePtr& patch);

	// libraries
	static LibraryPtr libraryFromJson(ProblemContainer& problems,
									  const QJsonObject& libObj,
									  const QString& filename);
	static QJsonObject libraryToJson(Library* library);

	// DEPRECATED: old 'plus' jar mods generated by the application
	static LibraryPtr plusJarModFromJson(ProblemContainer& problems,
										 const QJsonObject& libObj,
										 const QString& filename,
										 const QString& originalName);

	// new jar mods derived from libraries
	static LibraryPtr jarModFromJson(ProblemContainer& problems,
									 const QJsonObject& libObj,
									 const QString& filename);
	static QJsonObject jarModtoJson(Library* jarmod);

	// mods, also derived from libraries
	static LibraryPtr modFromJson(ProblemContainer& problems,
								  const QJsonObject& libObj,
								  const QString& filename);
	static QJsonObject modtoJson(Library* jarmod);
};
