.TH EMNV 1 "2002 Lut 16"
.SH NAZWA
emnv \- łatwy MNV, edytuj plik w MNVie z ustawieniami dla edycji bez
trybów
.SH SYNOPSIS
.br
.B emnv
[opcje] [plik ...]
.br
.B eview
.SH OPIS
.B eMNV
uruchamia
.B MNVa
i ustawia opcje tak by zachowywał się jak edytor bez trybów.
To jest cały czas MNV ale używany jako edytor wskaż-i-kliknij.
Zachowanie w stylu Notepada dla MS-Windows.
.B eMNV
będzie zawsze uruchomiony w GUI by włączyć menu i pasek narzędzi.
.PP
Przeznaczony tylko dla ludzi, którzy naprawdę nie mogą pracować
z MNVem w normalny sposób. Edycja będzie o wiele mniej efektywna.
.PP
.B eview
działa tak samo, ale zaczyna w trybie tylko do odczytu. Działa tak
samo jak emnv \-R.
.PP
Zobacz mnv(1) by poznać więcej szczegółów o MNVie, opcjach, itd.
.PP
Opcja 'insertmode' jest ustawiona by można było od razu wpisywać
tekst.
.br
Mapowania są ustawione tak by Kopiowanie i Wklejanie działało
z klawiszami MS-Windows. CTRL-X wycina, CTRL-C kopiuje a CTRL-V 
wkleja tekst. Użyj CTRL-Q by uzyskać oryginalne przeznaczenie
CTRL-V.
.SH OPCJE
Zobacz mnv(1).
.SH PLIKI
.TP 15
/usr/local/lib/mnv/emnv.mnv
Skrypt uruchamiania dla eMNVa.
.SH ZNANY JAKO
Znany jako "MNV dla frajerów".
Jeśli używasz eMNVa oczekuje się, że wyjmiesz chusteczkę do nosa,
zrobisz węzęł w każdym rogu i będziesz to nosił na głowie.
.SH ZOBACZ TAKŻE
mnv(1)
.SH AUTOR
Większość 
.B MNVa
została napisana przez Brama Moolenaara z dużą pomocą innych osób.
Zobacz menu Help/Credits.
