.TH MNVDIFF 1 "2021 June 13"
.SH 名前
mnvdiff \- 2 個から 8 個のファイルを MNV で開いて、その差分を表示する
.SH 書式
.br
.B mnvdiff
[options] file1 file2 [file3 [file4 [file5 [file6 [file7 [file8]]]]]]
.PP
.B gmnvdiff
.SH 説明
.B MNVdiff
は、2 個から 8 個のファイルを
.B MNV
で開きます。
ファイルは個別のウィンドウで開かれ、差分が強調表示されます。
同じファイルの別のバージョン間で、変更を確認したり、変更を移動したりするのが簡単になります。
.PP
MNV についての詳細は mnv(1) を参照してください。
.PP
.B gmnvdiff
という名前で起動された場合は GUI で起動します。
.PP
差分を強調表示するために、それぞれのウィンドウの 'diff' オプションがオンに設定されます。
.br
テキストを見やすくするために、オプションの 'wrap' と 'scrollbind' もオンに設定されます。
.br
 'foldmethod' オプションは "diff" に設定され、変更されていない行は折り畳まれます。
折り畳みの確認と開閉が簡単にできるように、'foldcolumn' は 2 に設定されます。
.SH オプション
行を並べて表示するために、"\-O" 引数を使ったときのように、ウィンドウは垂直分割されます。
ウィンドウを水平分割したい場合は "\-o" 引数を使ってください。
.PP
その他の引数については mnv(1) を参照してください。
.SH 関連項目
mnv(1)
.SH 著者
.B MNV
のほとんどの機能は Bram Moolenaar が開発し、多くの人が協力しました。
":help credits" を参照してください。
