.TH MNVDIFF 1 "30. marts 2001"
.SH NAVN
mnvdiff \- rediger to, tre eller fire version af en fil med MNV,
og vis forskellene
.SH SYNOPSIS
.br
.B mnvdiff
[tilvalg] fil1 fil2 [fil3 [fil4]]
.PP
.B gmnvdiff
.SH BESKRIVELSE
.B MNVdiff
starter
.B MNV
på to (eller tre eller fire) filer.
Hver fil får sit eget vindue.
Forskellene mellem filerne fremhæves.
Det er en fin måde til at inspicere ændringer og til at flytte ændringer fra
en version til en anden version af den samme fil.
.PP
Se mnv(1) for detaljer om selve MNV.
.PP
Når den startes som
.B gmnvdiff
, så starter den GUI'en, hvis den er tilgængelig.
.PP
I hvert vindue sættes 'diff'-valgmuligheden, som får forskellene
til at blive fremhævet.
.br
\'wrap'- og 'scrollbind'-valgmulighederne sættes for at få teksten til
at se godt ud.
.br
\'foldmethod'-valgmuligheden sættes til "diff", hvilket lægger områder af
linjer uden ændringer i en sammenfoldning. 'foldcolumn' sættes til to,
for at gøre det lettere at se sammenfoldningerne og åbne eller lukke dem.
.SH TILVALG
Lodrette opdelinger bruges til at opstille linjerne, som hvis "\-O"-argumentet
blev brugt.
Brug "\-o"-argumentet, for i stedet at bruge vandrette opdelinger.
.PP
Se mnv(1) for alle andre argumenter.
.SH SE OGSÅ
mnv(1)
.SH FORFATTER
Det meste af
.B MNV
blev lavet af Bram Moolenaar, med en masse hjælp fra andre.
Se ":help credits" i
.B MNV\c
\&.
