.TH MNVTUTOR 1 "3 décembre 2024"
.SH NAME
mnvtutor \- tutoriel MNV
.SH SYNOPSIS
.br
.B mnvtutor [\-l | \-\-language ISO639] [\-c | \-\-chapter NUMÉRO] [\-g | \-\-gui] [ISO639]
.br
.B mnvtutor [\-h | \-\-help]
.br
.B mnvtutor [\-\-list]
.SH DESCRIPTION
.B mnvtutor
lance le tutoriel
.BR "MNV" "."
.PP
.B mnvtutor
est utile pour les personnes souhaitant apprendre leurs premières
commandes
.BR "MNV" "."
.PP
L'argument optionel [ISO639] correspond aux deux ou trois lettres qui identifient
une langue, comme par exemple "it" ou "es".
.PP
.B mnvtutor
ne fait qu'ouvrir une copie temporaire des fichiers du tutoriel, il n'y
a donc aucun risque d'écraser les leçons.
.PP
.B MNV
est toujours lancé en mode
.B Vi
compatible.
.PP
.SH OPTIONS
.TP
.BR \-l ", " \-\-language\ \fIISO639\fR
Les deux ou trois lettres qui déterminent la langue, comme
par exemple 'it', 'es' ou 'bar'.
Par défaut, la langue locale du système est utilisée,
ou l'anglais sinon.
.TP
.BR \-c ", " \-\-chapter\ \fINUMÉRO\fR
Sélectionne le chapitre désiré. Par défaut, c'est le premier chapitre.
.TP
.BR \-g ", " \-\-gui
Lance
.B mnvtutor
avec une interface graphique de
.B MNV
si possible; sinon, revient à la version console.
.TP
.BR \-h ", " \-\-help
Affiche les informations d'usage.
.TP
.BR \-\-list
Affiche la liste des chapitres et des langues.
.SH EXEMPLES
Pour démarrer
.B mnvtutor
en français au premier chapitre:
.PP
.nf
.RS
mnvtutor fr
.RE
.fi
.PP
En anglais au chapitre deux:
.PP
.nf
.RS
mnvtutor -c2
.RE
.fi
.PP
Pour lancer (avec les commandes en format long) l'interface graphique,
pour le bavarois, au premier chapitre:
.PP
.nf
.RS
mnvtutor --language bar --chapter 1 --gui
.RE
.fi
.SH FICHIERS
.TP 15
/usr/local/share/mnv/mnv??/tutor/tutor1[.language]
Les fichiers du premier chapitre du
.B mnvtutor
\.
.TP 15
/usr/local/share/mnv/mnv??/tutor/tutor2[.language]
Les fichiers du deuxième chapitre du
.B mnvtutor
\.
.TP 15
/usr/local/share/mnv/mnv??/tutor/tutor.mnv
Le script
.B MNV
utilisé pour copier les fichier du
.B mnvtutor
\.
.SH AUTEUR
.B MNVtutor
a été écrit à l'origine pour Vi par Michael C. Pierce et Robert K. Ware, de la
Colorado School of Mines, en reprenant des idées émises par Charles Smith, de
la Colorado State University.
Courriel: bware@mines.colorado.edu (ne fonctionne plus).
.br
Il a été modifié pour
.B MNV
par Bram Moolenaar.
Pour connaitre le nom des traducteurs, consultez les fichiers textes du
tutoriel.
.SH VOIR AUSSI
mnv(1)
.SH TRADUCTION
Cette page de manuel a été traduite par David Blanchet
<david.blanchet@free.fr> 2004-12-27.
Mise à jour 2012-05-06, Dominique Pellé <dominique.pelle@gmail.com>.
Mise à jour 2025-06-16, Damien Lejay <damien@lejay.be>.
