#!/bin/csh
#
# Shell script for use with UNIX
# Starts up MNV with the terminal in 132 column mode
# Only works on VT-100 terminals and lookalikes
# You need to have a termcap entry "vt100-w". Same as vt100 but 132 columns.
#
set oldterm=$term
echo "[?3h"
setenv TERM vt100-w
mnv $*
set term=$oldterm
echo "[?3l"
