<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260222000000 extends AbstractMigration
{
    public function up(Schema $schema): void
    {

        $this->addSql("");
        $this->addSql("");
        $this->addSql("CREATE TABLE public_credential (id INT AUTO_INCREMENT NOT NULL, public_key_credential_id VARCHAR(255) NOT NULL, public_key LONGTEXT NOT NULL, sign_count INT NOT NULL, user_handle VARCHAR(255) NOT NULL, transports JSON NOT NULL, attestation_type VARCHAR(255) NOT NULL, credential_id LONGTEXT NOT NULL, trust_path JSON NOT NULL, aaguid CHAR(36) NOT NULL, user_id INT NOT NULL, INDEX IDX_9FED8926A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, date DATETIME NOT NULL, content LONGTEXT NOT NULL, description VARCHAR(255) DEFAULT NULL, metadata JSON DEFAULT NULL, category_id INT DEFAULT NULL, product_id INT DEFAULT NULL, INDEX IDX_1DD3995012469DE2 (category_id), INDEX IDX_1DD399504584665A (product_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE discussion_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE visit (id INT AUTO_INCREMENT NOT NULL, ip VARCHAR(255) DEFAULT NULL, browser VARCHAR(255) DEFAULT NULL, os VARCHAR(255) DEFAULT NULL, url VARCHAR(255) NOT NULL, visited_at DATETIME NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_437EE939A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE spdx_license (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, identifier VARCHAR(100) NOT NULL, is_osi_approved TINYINT NOT NULL, see_also LONGTEXT DEFAULT NULL, content LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_356C852772E836A (identifier), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE roadmap_item (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE roadmap_item_votes (roadmap_item_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_FE43351DDB21C47 (roadmap_item_id), INDEX IDX_FE43351DA76ED395 (user_id), PRIMARY KEY (roadmap_item_id, user_id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE license (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, usage_documentation LONGTEXT DEFAULT NULL, spdx_identifier VARCHAR(100) DEFAULT NULL, tagline VARCHAR(255) DEFAULT NULL, features JSON DEFAULT NULL, icon_class VARCHAR(100) DEFAULT NULL, license_category_id INT DEFAULT NULL, INDEX IDX_5768F419305384A4 (license_category_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE site_setting (id INT AUTO_INCREMENT NOT NULL, setting_key VARCHAR(255) NOT NULL, setting_value LONGTEXT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, category VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, UNIQUE INDEX UNIQ_64D05A535FA1E697 (setting_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE license_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, display_order INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE github_repository (id INT AUTO_INCREMENT NOT NULL, full_name VARCHAR(255) NOT NULL, installation_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_7A865C28DBC463C4 (full_name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE news_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, github_id VARCHAR(255) DEFAULT NULL, github_username VARCHAR(255) DEFAULT NULL, gitlab_id VARCHAR(255) DEFAULT NULL, gitlab_username VARCHAR(255) DEFAULT NULL, biography LONGTEXT DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, timezone VARCHAR(255) DEFAULT NULL, microsoft_id VARCHAR(255) DEFAULT NULL, minecraft_uuid VARCHAR(255) DEFAULT NULL, minecraft_access_token LONGTEXT DEFAULT NULL, minecraft_username VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, reset_password_token VARCHAR(255) DEFAULT NULL, reset_password_expires_at DATETIME DEFAULT NULL, email_change_token VARCHAR(255) DEFAULT NULL, new_email_pending VARCHAR(180) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, username VARCHAR(180) DEFAULT NULL, tick_api_token VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE app_showcase (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, developer VARCHAR(255) DEFAULT NULL, website_url VARCHAR(255) DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, short_description VARCHAR(255) DEFAULT NULL, is_featured TINYINT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE product (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, summary VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, about_content LONGTEXT DEFAULT NULL, version VARCHAR(50) DEFAULT NULL, download_url VARCHAR(255) DEFAULT NULL, github_url VARCHAR(255) DEFAULT NULL, features JSON DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, updated_at DATETIME NOT NULL, product_type VARCHAR(50) DEFAULT NULL, product_status VARCHAR(50) DEFAULT NULL, product_visibility VARCHAR(50) DEFAULT NULL, product_owner VARCHAR(255) DEFAULT NULL, allow_windows TINYINT NOT NULL, allow_macos TINYINT NOT NULL, allow_linux TINYINT NOT NULL, is_sparkle_enabled TINYINT NOT NULL, download_content_windows LONGTEXT DEFAULT NULL, download_content_macos LONGTEXT DEFAULT NULL, download_content_linux LONGTEXT DEFAULT NULL, use_html_windows TINYINT NOT NULL, use_html_macos TINYINT NOT NULL, use_html_linux TINYINT NOT NULL, landing_page_content LONGTEXT DEFAULT NULL, use_custom_landing_page TINYINT NOT NULL, requires_license TINYINT NOT NULL, price NUMERIC(10, 2) DEFAULT NULL, license_id INT DEFAULT NULL, INDEX IDX_D34A04AD460F904B (license_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE pull_request (id INT AUTO_INCREMENT NOT NULL, repository VARCHAR(255) NOT NULL, number INT NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(100) NOT NULL, state VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, labels JSON DEFAULT NULL, html_url VARCHAR(255) DEFAULT NULL, commits JSON DEFAULT NULL, body LONGTEXT DEFAULT NULL, diff LONGTEXT DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE license_comparison (id INT AUTO_INCREMENT NOT NULL, feature VARCHAR(255) NOT NULL, mit_apache VARCHAR(255) NOT NULL, gnu_gpl VARCHAR(255) NOT NULL, project_tick VARCHAR(255) NOT NULL, display_order INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE developer_portal_entry (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, display_order INT DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE user_license (id INT AUTO_INCREMENT NOT NULL, signed_at DATETIME NOT NULL, ip_address VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, signature_type VARCHAR(255) DEFAULT NULL, license_key VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, license_id INT NOT NULL, assigned_product_id INT DEFAULT NULL, INDEX IDX_F65EA13A76ED395 (user_id), INDEX IDX_F65EA13460F904B (license_id), INDEX IDX_F65EA137D25052B (assigned_product_id), INDEX idx_license_key (license_key), UNIQUE INDEX unique_user_product_license (user_id, assigned_product_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE cla_signature (id INT AUTO_INCREMENT NOT NULL, signed_at DATETIME NOT NULL, version VARCHAR(255) NOT NULL, github_username VARCHAR(255) NOT NULL, gitlab_username VARCHAR(255) DEFAULT NULL, sha VARCHAR(64) DEFAULT NULL, is_verified TINYINT NOT NULL, verification_token VARCHAR(100) DEFAULT NULL, verified_at DATETIME DEFAULT NULL, signature_image LONGTEXT DEFAULT NULL, signer_name VARCHAR(255) DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent LONGTEXT DEFAULT NULL, nonce VARCHAR(255) DEFAULT NULL, github_numeric_id VARCHAR(255) DEFAULT NULL, gitlab_numeric_id VARCHAR(255) DEFAULT NULL, email_hash VARCHAR(64) DEFAULT NULL, server_signature LONGTEXT DEFAULT NULL, pdf_path VARCHAR(255) DEFAULT NULL, pdf_hash VARCHAR(64) DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_D15049A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE heartbeat (id INT AUTO_INCREMENT NOT NULL, status TINYINT NOT NULL, response_time INT NOT NULL, message LONGTEXT DEFAULT NULL, timestamp DATETIME NOT NULL, ssl_days_remaining INT DEFAULT NULL, monitor_id INT NOT NULL, INDEX IDX_A7DEDD94CE1C902 (monitor_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE discussion_comment (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, thread_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_1C2A74D1E2904019 (thread_id), INDEX IDX_1C2A74D1F675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE monitor (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, active INT NOT NULL, type VARCHAR(20) NOT NULL, `interval` INT NOT NULL, retry_interval INT NOT NULL, max_retries INT NOT NULL, weight INT NOT NULL, method VARCHAR(10) DEFAULT NULL, body LONGTEXT DEFAULT NULL, headers LONGTEXT DEFAULT NULL, dns_resolve_type VARCHAR(255) DEFAULT NULL, dns_resolve_server VARCHAR(255) DEFAULT NULL, port INT DEFAULT NULL, expiry_notification INT NOT NULL, ignore_tls INT NOT NULL, upside_down INT NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE github_commit (id INT AUTO_INCREMENT NOT NULL, repository VARCHAR(255) NOT NULL, sha VARCHAR(100) NOT NULL, message LONGTEXT NOT NULL, author VARCHAR(100) NOT NULL, date DATETIME NOT NULL, html_url VARCHAR(255) DEFAULT NULL, diff LONGTEXT DEFAULT NULL, UNIQUE INDEX repo_sha_idx (repository, sha), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE handbook_entry (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, category VARCHAR(100) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE ecosystem_node (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, shortcut VARCHAR(50) NOT NULL, description VARCHAR(255) DEFAULT NULL, position_x INT NOT NULL, position_y INT NOT NULL, type VARCHAR(50) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE handbook_feedback (id INT AUTO_INCREMENT NOT NULL, helpful TINYINT NOT NULL, ip VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, entry_id INT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_35ADBC1CBA364942 (entry_id), INDEX IDX_35ADBC1CA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE discussion_thread (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, category_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_675C175B12469DE2 (category_id), INDEX IDX_675C175BF675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;");
        $this->addSql("ALTER TABLE public_credential ADD CONSTRAINT FK_9FED8926A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);");
        $this->addSql("ALTER TABLE news ADD CONSTRAINT FK_1DD3995012469DE2 FOREIGN KEY (category_id) REFERENCES news_category (id);");
        $this->addSql("ALTER TABLE news ADD CONSTRAINT FK_1DD399504584665A FOREIGN KEY (product_id) REFERENCES product (id);");
        $this->addSql("ALTER TABLE visit ADD CONSTRAINT FK_437EE939A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;");
        $this->addSql("ALTER TABLE roadmap_item_votes ADD CONSTRAINT FK_FE43351DDB21C47 FOREIGN KEY (roadmap_item_id) REFERENCES roadmap_item (id) ON DELETE CASCADE;");
        $this->addSql("ALTER TABLE roadmap_item_votes ADD CONSTRAINT FK_FE43351DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;");
        $this->addSql("ALTER TABLE license ADD CONSTRAINT FK_5768F419305384A4 FOREIGN KEY (license_category_id) REFERENCES license_category (id);");
        $this->addSql("ALTER TABLE product ADD CONSTRAINT FK_D34A04AD460F904B FOREIGN KEY (license_id) REFERENCES license (id);");
        $this->addSql("ALTER TABLE user_license ADD CONSTRAINT FK_F65EA13A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);");
        $this->addSql("ALTER TABLE user_license ADD CONSTRAINT FK_F65EA13460F904B FOREIGN KEY (license_id) REFERENCES license (id);");
        $this->addSql("ALTER TABLE user_license ADD CONSTRAINT FK_F65EA137D25052B FOREIGN KEY (assigned_product_id) REFERENCES product (id);");
        $this->addSql("ALTER TABLE cla_signature ADD CONSTRAINT FK_D15049A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);");
        $this->addSql("ALTER TABLE heartbeat ADD CONSTRAINT FK_A7DEDD94CE1C902 FOREIGN KEY (monitor_id) REFERENCES monitor (id) ON DELETE CASCADE;");
        $this->addSql("ALTER TABLE discussion_comment ADD CONSTRAINT FK_1C2A74D1E2904019 FOREIGN KEY (thread_id) REFERENCES discussion_thread (id);");
        $this->addSql("ALTER TABLE discussion_comment ADD CONSTRAINT FK_1C2A74D1F675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE;");
        $this->addSql("ALTER TABLE handbook_feedback ADD CONSTRAINT FK_35ADBC1CBA364942 FOREIGN KEY (entry_id) REFERENCES handbook_entry (id);");
        $this->addSql("ALTER TABLE handbook_feedback ADD CONSTRAINT FK_35ADBC1CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id);");
        $this->addSql("ALTER TABLE discussion_thread ADD CONSTRAINT FK_675C175B12469DE2 FOREIGN KEY (category_id) REFERENCES discussion_category (id);");
        $this->addSql("ALTER TABLE discussion_thread ADD CONSTRAINT FK_675C175BF675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE;");
    }

    public function down(Schema $schema): void
    {
    }
}
