name: "MeshMC: Release"

on:
  workflow_call:

permissions: {}

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/meshmc-build.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      build-type: Release
      environment: Release
    secrets: inherit


