name: "neozip: Fuzz"

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: neozip-fuzz-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  fuzzing:
    name: Fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build Fuzzers
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: 'neozip'
          dry-run: false
          project-src-path: neozip

      - name: Run Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: 'neozip'
          fuzz-seconds: 600
          dry-run: false

      - name: Upload Crash
        uses: actions/upload-artifact@v4
        if: failure() && steps.build.outcome == 'success'
        with:
          name: neozip-fuzz-artifacts
          path: ./out/artifacts
