name: "neozip: Fuzz"

on:
  push:
    branches: [master, develop]
    paths:
      - 'neozip/**'
      - '.github/workflows/neozip-fuzz.yml'
  pull_request:
    paths:
      - 'neozip/**'
      - '.github/workflows/neozip-fuzz.yml'
  workflow_dispatch:

concurrency:
  group: neozip-fuzz-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  fuzzing:
    name: Fuzzing
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: 'zlib-ng'
          dry-run: false

      - name: Run Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: 'zlib-ng'
          fuzz-seconds: 600
          dry-run: false

      - name: Upload Crash
        uses: actions/upload-artifact@v4
        if: failure() && steps.build.outcome == 'success'
        with:
          name: neozip-fuzz-artifacts
          path: ./out/artifacts
